// pages/chat.vue
<script setup lang="ts">
    import { useAlertStore } from '~/stores/store';

    const supabase = useSupabaseClient();
    const user = useSupabaseUser();
    const alertStore = useAlertStore();

    interface User{
        id: number,
        user_id: string,
        full_name: string,
        friends:string[],
        pfp: string,
        date_joined: string
    }

    interface Chat{
        id: number,
        msg: string,
        sent_by: string,
        sent_to: string
    }

    const customUser: Ref<User> = ref({ id: 0, user_id: "", full_name: "", friends: [], pfp: "", date_joined: ""});
    const friends: Ref<User[]> = ref([]);
    const currentFriend: Ref<User> = ref({ id: 0, user_id: "", full_name: "", friends: [], pfp: "", date_joined: ""});
    const chats: Ref<Chat[]> = ref([]);

    let msg = "";

    onMounted(async () => {
        if (!user.value) return;
        
        const { data: data1, error: error1 } = await supabase.from('users').select().eq('user_id', user.value.id).single();
        if(error1) throw error1
        else customUser.value = data1;

        const { data: data2, error: error2 } = await supabase.from('users').select().in('user_id', customUser.value.friends);
        if(error2) throw error2;
        else friends.value = data2;
    });

    async function setFriend(friendIn: User){
        currentFriend.value = friendIn;
        getChats();
    }

    async function getChats(){
        const tempArray:string[] = [customUser.value.user_id, currentFriend.value.user_id];
        const {data, error} = await supabase.from("chats").select().in("sent_by", tempArray).in("sent_to", tempArray).order("id", { ascending: false });
        if(error) throw error;
        else chats.value = data;
    }

    async function sendChat(){
        if(msg === ""){
            alertStore.msg = "You need to enter text into the text box.";
            alertStore.type = "error";
            alertStore.timesShown++;
            return;
        }

        //@ts-expect-error
        const { error } = await supabase.from("chats").insert({ msg: msg, sent_by: customUser.value.user_id, sent_to: currentFriend.value.user_id });
        if(error) throw error;
        else{
            msg = "";
            getChats();
        }
    }

</script>

<template>
    <div class="flex h-fullscreen">
        <aside class="w-1/6 border-r-2 border-r-snow/45">
            <h2 class="text-5xl font-mono font-semibold">Friends</h2>
            <ul class="pl-2">
                <li v-for="friend in friends" class="flex items-center border-b border-b-snow/25 pb-1.5 last:pb-0 last:border-b-transparent">
                    <img :src="friend.pfp" alt="Friend pfp" width="32px" height="32px" />
                    <span class="text-xl text-aero-100 flex flex-grow h-fit">{{ friend.full_name }}</span>
                    <button @click="setFriend(friend)" class="hover:text-aero-200 transition-colors duration-200 ease-in">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                        </svg>
                    </button>
                </li>
            </ul>
        </aside>
        <main v-if="currentFriend.full_name != ''" class="w-5/6 flex flex-col pb-2">
            <section class="w-screen flex h-16 items-center">
                <img :src="currentFriend.pfp" alt="Friend pfp" width="48px" height="48px" />
                <h1 class="text-6xl font-mono font-semibold bg-clip-text text-transparent bg-gradient-to-r from-snow to-65% to-aero-100 w-fit">{{ currentFriend.full_name }}</h1>
            </section>
            <ul id="chatbox" class="ml-2 pb-2 overflow-y-scroll max-h-chatView flex w-screen flex-col-reverse">
                <li v-for="chat in chats" class="flex space-x-2">
                    <p v-if="chat.sent_by === currentFriend.user_id"><span class="text-sky-300">{{ currentFriend.full_name }}</span>:</p>
                    <p v-else-if="chat.sent_by === customUser.user_id"><span class="text-aero-300">{{ customUser.full_name }}</span>:</p>
                    <p>{{ chat.msg }}</p>
                </li>
            </ul>
            <div class="flex flex-grow"></div>
            <div class="mr-8 h-8 flex">
                <input @keypress.enter="sendChat" type="text" v-model="msg" placeholder="Enter message" class="w-full bg-shark-900 text-lg rounded-l-sm pl-2 h-8 placeholder:italic outline-0">
                <button @click="sendChat" class="bg-shark-900 rounded-r-sm pr-2 hover:text-aero-100 transition-colors duration-200 ease-out">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
                    </svg>
                </button>
            </div>
        </main>
        <main v-else id="noChats" class="w-5/6 flex flex-col justify-center items-center">
            <h1 class="text-8xl uppercase font-mono font-black bg-clip-text border-b-[3px] border-b-snow/15 px-4 text-transparent bg-gradient-to-r from-snow to-65% to-aero-100">No friend picked</h1>
            <p class="text-2xl">Click the ">" next to one of your friends to chat with them!</p>
        </main>
    </div>
</template>

<style scoped>
    #chatbox::-webkit-scrollbar{
        background: transparent;
    }

    #noChats{
        background-color: #201e1f;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'%3E%3Cg fill-rule='evenodd'%3E%3Cg fill='%23c9ffe2' fill-opacity='0.05'%3E%3Cpath opacity='.5' d='M96 95h4v1h-4v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4h-9v4h-1v-4H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15v-9H0v-1h15V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h9V0h1v15h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9h4v1h-4v9zm-1 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm9-10v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm9-10v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm9-10v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-10 0v-9h-9v9h9zm-9-10h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9zm10 0h9v-9h-9v9z'/%3E%3Cpath d='M6 5V0H5v5H0v1h5v94h1V6h94V5H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
    }
</style>

// src/pages/chat.tsx
import { useEffect, useState } from "react";
import { supabase } from "../supabaseClient";
import Layout from "../components/layout";
import { useNavigate } from "react-router-dom";

interface Chat{
    id: number,
    msg: string,
    sent_by: string,
    sent_to: string
}

interface User{
    id: number,
    user_id: string,
    first_name: string,
    last_name:string,
    friends:string[],
    pfp: string
}

export default function Chat(){
    const nav = useNavigate();

    const [user, setUser] = useState<User>({id: -1, user_id: "", first_name: "", last_name: "", friends: [], pfp: ""});
    const [currentFriend, setFriend] = useState<User>({id: -1, user_id: "", first_name: "", last_name: "", friends: [], pfp: ""});

    const [chats, setChats] = useState<Chat[]>([]);
    const [friends, setFriends] = useState<User[]>([]);

    const [msg, setMsg] = useState("");
    const [uuid, setUuid] = useState("");

    let tempFriends:string[] = [];
  
    useEffect(() => {
        getUser();
    }, []);

    async function getUser(){
        await supabase.auth.getUser().then((val) => {
            if(val.data?.user){
                setCurrentUser(val.data.user.id);
                getTempFriends(val.data.user.id);
            } else{
                nav("/user");
            }
        });
    }

    async function setCurrentUser(uuid:string){
        const {data, error} = await supabase.from("users").select().eq("user_id", uuid).single();
        if(error) throw error;
        else setUser(data)
    }

    async function getTempFriends(uuid:string) {
        const {data, error} = await supabase.from("users").select("friends").eq("user_id", uuid).single();
        if(error) throw error;
        else{
            setUuid(uuid);
            tempFriends = JSON.parse(JSON.stringify(data.friends))
            getFinalFriends();
        }
    }

    async function getFinalFriends() {
        const {data, error} = await supabase.from("users").select().in("user_id", tempFriends);
        if(error) throw error;
        else setFriends(data)
    }

    async function getChats(friendId:string, fromAside:boolean) {
        const tempArray:string[] = [uuid, friendId];
        const {data, error} = await supabase.from("chats").select().in("sent_by", tempArray).in("sent_to", tempArray).order("id", {ascending: false});
        if(error) throw error;
        else{
            if(fromAside) getCurrentFriend(friendId)
            setChats(data);
        }
    }

    async function getCurrentFriend(friendId:string){
        const {data, error} = await supabase.from("users").select().eq("user_id", friendId).single();
        if(error) throw error;
        else setFriend(data);
    }

  
    async function createChat(){
        const {error} = await supabase.from("chats").insert({msg: msg, sent_by: uuid, sent_to: currentFriend.user_id}).single();
        if(error) throw error;
        else{
            setMsg("");
            getChats(currentFriend.user_id, false)
        }
    }

    return(
        <Layout>
            <div className="flex h-fullScreen">
                <aside className="w-1/6 border-r-2 border-slate-50">
                    <section className="border-b-1 flex items-center">
                        <h2 className="flex flex-grow text-5xl tracking-wider font-bold">Friends</h2>
                        {/* <button className="flex w-fit h-fit mr-2 group rounded-full p-1.5 shadow-sm transition-all duration-150 ease-in hover:scale-[1.075] hover:bg-zinc-700 hover:shadow-md hover:shadow-green-400/25">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 transition-color delay-75 duration-150 ease-in group-hover:text-green-400">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" />
                            </svg>
                        </button> */}
                    </section>
                    <ul className="divide-y-1 divide-slate-700">
                        {friends.map((friend:User) => (
                            <li className="text-xl flex justify-center px-2 py-1.5">
                                <div className="flex flex-grow">
                                    <img src={friend.pfp} alt="This user's profile picture" className="w-8 h-8 rounded-full" />
                                    <span>{friend.first_name} {friend.last_name}</span>
                                </div>
                                <button onClick={() => getChats(friend.user_id, true)} className="group rounded-full p-0.5 shadow-sm hover:shadow-md hover:shadow-green-400/25 hover:bg-zinc-700 hover:scale-110 transition-all duration-150 ease-in">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="transition-color h-6 w-6 delay-75 duration-150 ease-in group-hover:text-green-400">
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                                    </svg>
                                </button>
                            </li>
                        ))}
                    </ul>
                </aside>
                <main className="w-5/6 h-full flex flex-col">
                    <ol className="flex flex-col-reverse flex-grow px-2">
                        {chats.map((chat:Chat) => (
                            <li className="text-lg">
                                {chat.sent_by === uuid ? 
                                    <div>
                                        <span className="text-green-400">{user.first_name}</span>
                                        <span>: {chat.msg}</span>
                                    </div>
                                :
                                    <div>
                                        <span className="text-cyan-400">{currentFriend.first_name}</span>
                                        <span>: {chat.msg}</span>
                                    </div>
                                }
                            </li>
                        ))}
                    </ol>
                    <section className="self-end flex w-full px-4 py-2">
                        <input type="text" name="msg" required value={msg} onChange={(e) => setMsg(e.target.value)} className="flex flex-grow bg-slate-700 rounded-l-md px-1" />
                        <button onClick={() => createChat()} className="bg-slate-700 rounded-r-md px-1.5 py-0.5 group">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 transition-color duration-150 ease-in group-hover:text-green-400">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                            </svg>
                        </button>
                    </section>
                </main>
            </div>
        </Layout>
    )
}
